// data.jsx — Maison Léa: Amazon affiliate edition (généré automatiquement)
const AMAZON_DATA_UPDATED_AT = "2026-08-26T04:56:57.173Z";
const COLLECTIONS = [
  { id:'lingerie',   label:'Lingerie',          fr:'Soutiens-gorge, culottes, bodies', count: 4 },
  { id:'nuit',       label:'Nuit & loungewear', fr:'Nuisettes, peignoirs, kimonos',     count: 3 },
  { id:'sensualite', label:'Sensualité',        fr:'Accessoires intimes & jeux',         count: 3, adult:true },
  { id:'erotisme',   label:'Érotisme',          fr:'Lecture, jeux coquins, fantaisies',  count: 3, adult:true },
  { id:'soins',      label:'Soins intimes',     fr:'Lubrifiants, huiles, bougies',       count: 3 },
  { id:'cadeaux',    label:'Coffrets',          fr:'Édition limitée, idées cadeaux',    count: 2 },
];

const PRODUCTS = [
  {
    "id": 1,
    "cat": "lingerie",
    "name": "Femme Dentelle Ensemble de Lingerie Sexy Transparente 2 P...",
    "sub": "Marque · PARUPRUP",
    "price": "7,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FZTWH9W9",
    "image": "https://m.media-amazon.com/images/I/419RdnKYOvL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FZTWH9W9?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 2,
    "cat": "lingerie",
    "name": "Femme Dentelle Ensemble de Lingerie Sexy Transparente 2 P...",
    "sub": "Marque · PARUPRUP",
    "price": "7,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FZTL81YF",
    "image": "https://m.media-amazon.com/images/I/41DGJFSe-xL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FZTL81YF?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 3,
    "cat": "lingerie",
    "name": "Avidlove Sexy Ensemble de Lingerie pour Femme Dentelle Bo...",
    "sub": "Marque · Avidlove",
    "price": "24,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0DH2KQQ9P",
    "image": "https://m.media-amazon.com/images/I/41A9dPftREL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DH2KQQ9P?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 4,
    "cat": "lingerie",
    "name": "ROSVAJFY Ensemble de Lingerie Sexy pour Femme en Dentelle...",
    "sub": "Marque · ROSVAJFY",
    "price": "11,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0D7ZRXC5J",
    "image": "https://m.media-amazon.com/images/I/417Whbn2Q+L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0D7ZRXC5J?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 5,
    "cat": "nuit",
    "name": "Marvmys Nuisette Femme Sexy Chemise de Nuit Dentelle Slin...",
    "sub": "Marque · Marvmys",
    "price": "16,09 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0CH37GP6T",
    "image": "https://m.media-amazon.com/images/I/41M83PaHP8L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CH37GP6T?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 6,
    "cat": "nuit",
    "name": "Marvmys Nuisette Femme Sexy Chemise de Nuit Dentelle Slin...",
    "sub": "Marque · Marvmys",
    "price": "10,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B09NGG1YQS",
    "image": "https://m.media-amazon.com/images/I/41IhYqdelpL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09NGG1YQS?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 7,
    "cat": "nuit",
    "name": "Lovasy Nuisette Femme Satin Spaghetti Nuisette en Soie po...",
    "sub": "Marque · Lovasy",
    "price": "10,79 €",
    "was": "11,99 €",
    "off": "-10%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0B92Y1P19",
    "image": "https://m.media-amazon.com/images/I/31bpGqsDtsL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0B92Y1P19?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 8,
    "cat": "sensualite",
    "name": "Godemichets Gode Vibro-masseur va et Vient, 20cm Gode Ven...",
    "sub": "Marque · Cosyfun",
    "price": "25,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0FF9R919P",
    "image": "https://m.media-amazon.com/images/I/41-5OkX47fL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FF9R919P?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 9,
    "cat": "sensualite",
    "name": "Unikrealer Rabbit Vibromasseurs Feminin Clitoridien Sexto...",
    "sub": "Marque · Unikrealer",
    "price": "21,99 €",
    "was": "23,95 €",
    "off": "-8%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0F1CKJ5Q1",
    "image": "https://m.media-amazon.com/images/I/31N264dHuwL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0F1CKJ5Q1?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 10,
    "cat": "sensualite",
    "name": "Gode Vibromasseurs Feminin Clitoridien va et vient APP Si...",
    "sub": "Marque · Cacuola",
    "price": "20,99 €",
    "was": "21,99 €",
    "off": "-5%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0FDQ1JTS4",
    "image": "https://m.media-amazon.com/images/I/213eknRvC7L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FDQ1JTS4?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 11,
    "cat": "erotisme",
    "name": "JUDUKU OSMOOZ Red - Jeu Couple - Jeux de société - Jeu de...",
    "sub": "Marque · ATM Gaming",
    "price": "14,99 €",
    "was": "19,99 €",
    "off": "-25%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0BF6192CK",
    "image": "https://m.media-amazon.com/images/I/41ZbS5+L5jL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0BF6192CK?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 12,
    "cat": "erotisme",
    "name": "CARTA SUTRA - Jeu Couple - Jeux de société - Jeu de Carte...",
    "sub": "Marque · CARTA SUTRA",
    "price": "24,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B09CB784JD",
    "image": "https://m.media-amazon.com/images/I/41hfFcN33nL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09CB784JD?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 13,
    "cat": "erotisme",
    "name": "JUDUKU Jeu Couple - OSMOOZ Couple - 180 Cartes fabriquées...",
    "sub": "Marque · ATM Gaming",
    "price": "14,99 €",
    "was": "17,44 €",
    "off": "-14%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0926YDQNS",
    "image": "https://m.media-amazon.com/images/I/41cUNIWxbHL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0926YDQNS?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 14,
    "cat": "soins",
    "name": "Natessance huile de massage ylang ylang éveil des sens 100ml",
    "sub": "Marque · Natessance",
    "price": "5,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B015V1UVNS",
    "image": "https://m.media-amazon.com/images/I/31V-Als3A5L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B015V1UVNS?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 15,
    "cat": "soins",
    "name": "Huile de Massage Monoï, Relaxante et Aphrodisiaque, Hydra...",
    "sub": "Marque · bleu & marine Bretania",
    "price": "14,90 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B01LBK1VIW",
    "image": "https://m.media-amazon.com/images/I/41AfEk+-m3L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B01LBK1VIW?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 16,
    "cat": "soins",
    "name": "Yum'Lube - Huile de Massage Comestible Érotique Vanille -...",
    "sub": "Marque · Yum'Lube",
    "price": "16,90 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B0CNZDGLH4",
    "image": "https://m.media-amazon.com/images/I/31-yipbCXTL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CNZDGLH4?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 17,
    "cat": "cadeaux",
    "name": "YINUO LIGHT coffret cadeau de bougies parfumées pour femm...",
    "sub": "Marque · YINUO LIGHT",
    "price": "22,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0D4YVYXJZ",
    "image": "https://m.media-amazon.com/images/I/51yagU2JYmL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0D4YVYXJZ?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 18,
    "cat": "cadeaux",
    "name": "RSLOVE Lingerie Sexy pour Femme Soutien-Gorge et Culotte ...",
    "sub": "Marque · RSLOVE",
    "price": "23,99 €",
    "was": "35,99 €",
    "off": "-33%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B08VFHJC2K",
    "image": "https://m.media-amazon.com/images/I/41eQ5iqqXPL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B08VFHJC2K?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  }
];

const PROMISES = [
  { kicker:'01', title:'Sélection éditoriale', body:'Maison Léa compare et organise des produits disponibles sur Amazon selon des critères utiles.' },
  { kicker:'02', title:'Prix vérifiés automatiquement', body:'Les prix sont affichés uniquement lorsqu\u2019ils ont été actualisés récemment via l\u2019API Amazon.' },
  { kicker:'03', title:'Transparence totale',          body:'Liens affiliés signalés clairement. Une commission Amazon nous rémunère, jamais vous.' },
  { kicker:'04', title:'Achat chez le vendeur',         body:'Vérifiez le vendeur, la livraison, les retours et la disponibilité directement sur Amazon.' },
];

const EDITORIAL = {
  kicker:'LE GUIDE · ÉDITION N°1',
  title:'Mes indispensables intimes.',
  excerpt:'Maison Léa partage une sélection éditoriale du moment, du soutien-gorge sans armatures au massage sensoriel. Prix et disponibilité sont confirmés sur Amazon.',
  read:'8 min'
};

const STATS = [
  { num:'18', label:'produits sélectionnés' },
  { num:'6', label:'territoires' },
  { num:'24h', label:'fraîcheur maximale des prix' },
  { num:'100%', label:'liens affiliés signalés' },
];

Object.assign(window, { AMAZON_DATA_UPDATED_AT, COLLECTIONS, PRODUCTS, PROMISES, EDITORIAL, STATS });
