// data.jsx — Maison Léa: Amazon affiliate edition (généré automatiquement)
const AMAZON_DATA_UPDATED_AT = "2026-09-21T09:57:46.466Z";
const COLLECTIONS = [
  { id:'lingerie',   label:'Lingerie',          fr:'Soutiens-gorge, culottes, bodies', count: 13 },
  { id:'nuit',       label:'Nuit & loungewear', fr:'Nuisettes, peignoirs, kimonos',     count: 12 },
  { id:'sensualite', label:'Sensualité',        fr:'Accessoires intimes & jeux',         count: 11, adult:true },
  { id:'erotisme',   label:'Érotisme',          fr:'Lecture, jeux coquins, fantaisies',  count: 11, adult:true },
  { id:'soins',      label:'Soins intimes',     fr:'Lubrifiants, huiles, bougies',       count: 11 },
  { id:'cadeaux',    label:'Coffrets',          fr:'Édition limitée, idées cadeaux',    count: 10 },
];

const PRODUCTS = [
  {
    "id": 1,
    "cat": "lingerie",
    "name": "Femme Dentelle Ensemble de Lingerie Sexy Transparente 2 P...",
    "sub": "Marque · PARUPRUP",
    "price": "7,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FZTWH9W9",
    "image": "https://m.media-amazon.com/images/I/419RdnKYOvL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FZTWH9W9?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 2,
    "cat": "lingerie",
    "name": "Femme Dentelle Ensemble de Lingerie Sexy Transparente 2 P...",
    "sub": "Marque · PARUPRUP",
    "price": "7,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FZTL81YF",
    "image": "https://m.media-amazon.com/images/I/41DGJFSe-xL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FZTL81YF?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 3,
    "cat": "lingerie",
    "name": "OHWHOA 4 Pièces Ensemble Lingerie Femme Babydolls avec Ba...",
    "sub": "Marque · OHWHOA",
    "price": "10,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0CT36H533",
    "image": "https://m.media-amazon.com/images/I/41UwiUCUYEL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CT36H533?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 4,
    "cat": "lingerie",
    "name": "Femme Dentelle Ensemble de Lingerie Sexy Transparente 2 P...",
    "sub": "Marque · PARUPRUP",
    "price": "7,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FZTJC9G7",
    "image": "https://m.media-amazon.com/images/I/41-eGkOta1L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FZTJC9G7?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 5,
    "cat": "lingerie",
    "name": "Femme Dentelle Ensemble de Lingerie Sexy Transparente 2 P...",
    "sub": "Marque · PARUPRUP",
    "price": "8,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FZTNPMFB",
    "image": "https://m.media-amazon.com/images/I/41Xhfhg+alL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FZTNPMFB?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 6,
    "cat": "lingerie",
    "name": "ROSVAJFY Ensemble de Lingerie Sexy pour Femme en Dentelle...",
    "sub": "Marque · ROSVAJFY",
    "price": "11,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0D7ZRXC5J",
    "image": "https://m.media-amazon.com/images/I/417Whbn2Q+L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0D7ZRXC5J?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 7,
    "cat": "lingerie",
    "name": "Avidlove Ensemble de Lingerie pour Femme Dentelle 4 Pièce...",
    "sub": "Marque · Avidlove",
    "price": "24,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0DH2KQQ9P",
    "image": "https://m.media-amazon.com/images/I/41A9dPftREL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DH2KQQ9P?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 8,
    "cat": "lingerie",
    "name": "ROSVAJFY Ensemble de Lingerie Sexy pour Femme en Dentelle...",
    "sub": "Marque · ROSVAJFY",
    "price": "11,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0D7ZSQNYZ",
    "image": "https://m.media-amazon.com/images/I/41jRXINDUQL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0D7ZSQNYZ?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 9,
    "cat": "lingerie",
    "name": "DOBREVA Femme Soutien Gorge Balconnet avec Armature Noir 90A",
    "sub": "Marque · DOBREVA",
    "price": "32,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FCY7KZ63",
    "image": "https://m.media-amazon.com/images/I/41ZenhmTGtL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FCY7KZ63?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 10,
    "cat": "lingerie",
    "name": "Avidlove Soutien-Gorge Balconnet pour Femmes Dirndl Armat...",
    "sub": "Marque · Avidlove",
    "price": "18,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FJWJJMJB",
    "image": "https://m.media-amazon.com/images/I/41NAs+IHUsL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FJWJJMJB?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 11,
    "cat": "lingerie",
    "name": "Avidlove Soutien-Gorge Balconnet pour Femmes Dirndl Armat...",
    "sub": "Marque · Avidlove",
    "price": "18,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FJWNP3YT",
    "image": "https://m.media-amazon.com/images/I/41y8GiT92xL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FJWNP3YT?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 12,
    "cat": "lingerie",
    "name": "Avidlove Soutien-Gorge Balconnet pour Femmes à Armatures ...",
    "sub": "Marque · Avidlove",
    "price": "18,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B0FJWQRD4P",
    "image": "https://m.media-amazon.com/images/I/41mtqrk3WnL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FJWQRD4P?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 13,
    "cat": "lingerie",
    "name": "Cotonella, Soutien-Gorge Balconnet Vera avec Armatures",
    "sub": "Marque · Cotonella",
    "price": "11,90 €",
    "was": "12,62 €",
    "off": "-6%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#8b1d2c",
    "asin": "B06X8YRJ3Z",
    "image": "https://m.media-amazon.com/images/I/31FpEZXFtoL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B06X8YRJ3Z?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 14,
    "cat": "nuit",
    "name": "Marvmys Nuisette Femme Sexy Chemise de Nuit Dentelle Slin...",
    "sub": "Marque · Marvmys",
    "price": "14,99 €",
    "was": "16,09 €",
    "off": "-7%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0CH37GP6T",
    "image": "https://m.media-amazon.com/images/I/41M83PaHP8L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CH37GP6T?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 15,
    "cat": "nuit",
    "name": "Litherday Chemise de Nuit Femme Satin Nuisette Sling Robe...",
    "sub": "Marque · Litherday",
    "price": "10,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B09C8CWKCH",
    "image": "https://m.media-amazon.com/images/I/41bw-OrW8+L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09C8CWKCH?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 16,
    "cat": "nuit",
    "name": "Marvmys Nuisette Femme Sexy Chemise de Nuit Dentelle Slin...",
    "sub": "Marque · Marvmys",
    "price": "10,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B09NGG1YQS",
    "image": "https://m.media-amazon.com/images/I/41IhYqdelpL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09NGG1YQS?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 17,
    "cat": "nuit",
    "name": "Vlazom Chemise Nuisette de Nuit Femme Satin Sexy Bretelle...",
    "sub": "Marque · Vlazom",
    "price": "9,99 €",
    "was": "12,99 €",
    "off": "-23%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B07QH6H1HL",
    "image": "https://m.media-amazon.com/images/I/3133PdQsV8L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B07QH6H1HL?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 18,
    "cat": "nuit",
    "name": "Bresdk Chemise Homme de Nuit en Satin pour Femme Col en V...",
    "sub": "Marque · Bresdk",
    "price": "13,99 €",
    "was": "13,99 €",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0DBQ39GCQ",
    "image": "https://m.media-amazon.com/images/I/41npZvXa1zL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DBQ39GCQ?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 19,
    "cat": "nuit",
    "name": "Lovasy Nuisette Femme Satin Spaghetti Nuisette en Soie po...",
    "sub": "Marque · Lovasy",
    "price": "10,79 €",
    "was": "11,99 €",
    "off": "-10%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0B92Y1P19",
    "image": "https://m.media-amazon.com/images/I/31bpGqsDtsL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0B92Y1P19?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 20,
    "cat": "nuit",
    "name": "Bresdk Chemise Homme de Nuit en Satin pour Femme Col en V...",
    "sub": "Marque · Bresdk",
    "price": "11,49 €",
    "was": "13,99 €",
    "off": "-18%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0D53LVGKV",
    "image": "https://m.media-amazon.com/images/I/41qASmBL9cL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0D53LVGKV?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 21,
    "cat": "nuit",
    "name": "BABEYOND Kimono Femme Long en Satin - Peignoir Léger Impr...",
    "sub": "Marque · BABEYOND",
    "price": "29,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B075KZTMLJ",
    "image": "https://m.media-amazon.com/images/I/41abpw0N5bL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B075KZTMLJ?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 22,
    "cat": "nuit",
    "name": "Lovasy Peignoir Satin Femme Mariage en Dentelle Robe de C...",
    "sub": "Marque · Lovasy",
    "price": "14,24 €",
    "was": "16,99 €",
    "off": "-16%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0DQWDYMVB",
    "image": "https://m.media-amazon.com/images/I/41hDzezdPxL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DQWDYMVB?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 23,
    "cat": "nuit",
    "name": "Vlazom Kimono Femme Satin Mariage Bridesmaid Peignoir Man...",
    "sub": "Marque · Vlazom",
    "price": "11,99 €",
    "was": "14,99 €",
    "off": "-20%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B07FMBPHPN",
    "image": "https://m.media-amazon.com/images/I/31snRRvxi8L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B07FMBPHPN?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 24,
    "cat": "nuit",
    "name": "Lovasy Peignoir Satin Femme Mariage Peignoir en Soie Cour...",
    "sub": "Marque · Lovasy",
    "price": "12,74 €",
    "was": "14,99 €",
    "off": "-15%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0C7Z3XKL9",
    "image": "https://m.media-amazon.com/images/I/41KGg2q3oxL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0C7Z3XKL9?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 25,
    "cat": "nuit",
    "name": "Sopesil Peignoir Satin Femme Robes Longues pour Femmes Ro...",
    "sub": "Marque · Sopesil",
    "price": "16,99 €",
    "was": "19,99 €",
    "off": "-15%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a2e1f",
    "asin": "B0CSJR3C3Z",
    "image": "https://m.media-amazon.com/images/I/41Lhk9V1iTL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CSJR3C3Z?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 26,
    "cat": "sensualite",
    "name": "Godemichets Gode Vibro-masseur va et Vient, 20cm Gode Ven...",
    "sub": "Marque · Cosyfun",
    "price": "21,99 €",
    "was": "24,99 €",
    "off": "-12%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0FF9R919P",
    "image": "https://m.media-amazon.com/images/I/41-5OkX47fL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FF9R919P?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 27,
    "cat": "sensualite",
    "name": "Unikrealer Rabbit Vibromasseurs Feminin Clitoridien Sexto...",
    "sub": "Marque · Unikrealer",
    "price": "21,99 €",
    "was": "22,99 €",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0F1CKJ5Q1",
    "image": "https://m.media-amazon.com/images/I/31N264dHuwL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0F1CKJ5Q1?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 28,
    "cat": "sensualite",
    "name": "Godemichets Realiste 23 cm va et vient Silencieux Télécom...",
    "sub": "Marque · Tagnaff",
    "price": "30,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0G4R4CC78",
    "image": "https://m.media-amazon.com/images/I/31UwA0cAleL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0G4R4CC78?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 29,
    "cat": "sensualite",
    "name": "Gode Vibromasseurs Feminin Clitoridien va et vient APP Si...",
    "sub": "Marque · Cacuola",
    "price": "19,99 €",
    "was": "21,99 €",
    "off": "-9%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0FDQ1JTS4",
    "image": "https://m.media-amazon.com/images/I/213eknRvC7L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FDQ1JTS4?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 30,
    "cat": "sensualite",
    "name": "Sex Toys Vibromasseur Oeuf Vibrant Femme à Distance Telec...",
    "sub": "Marque · Kaiagame",
    "price": "16,99 €",
    "was": "19,99 €",
    "off": "-15%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0CRKL35YT",
    "image": "https://m.media-amazon.com/images/I/41kKstqk4pL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CRKL35YT?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 31,
    "cat": "sensualite",
    "name": "Gode Vibro-masseur Va et Vient Sex Toys - Gode Xxl Réalis...",
    "sub": "Marque · Banysin",
    "price": "23,79 €",
    "was": "25,99 €",
    "off": "-8%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0FFMGW6G9",
    "image": "https://m.media-amazon.com/images/I/31IOJ6cg+qL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FFMGW6G9?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 32,
    "cat": "sensualite",
    "name": "Gode Femme Sex Vibromasseur Feminin Clitoridien Va et Vie...",
    "sub": "Marque · AZOI",
    "price": "24,99 €",
    "was": "26,99 €",
    "off": "-7%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0FNRPBZMR",
    "image": "https://m.media-amazon.com/images/I/415M2F71L2L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FNRPBZMR?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 33,
    "cat": "sensualite",
    "name": "Vibromasseurs Feminin va et vient avec Léchage Réaliste G...",
    "sub": "Marque · Unikrealer",
    "price": "34,99 €",
    "was": "35,99 €",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0G7G3QZ95",
    "image": "https://m.media-amazon.com/images/I/41ef25+XlJL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0G7G3QZ95?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 34,
    "cat": "sensualite",
    "name": "Sextoyse Couple Plaisir Anneau Penien - Anneau Homme 4 en...",
    "sub": "Marque · rinofans",
    "price": "25,98 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0DJY433T4",
    "image": "https://m.media-amazon.com/images/I/41w5YgZWJoL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DJY433T4?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 35,
    "cat": "sensualite",
    "name": "Cacuola Anneau Penien - Anneau Homme Vibrant Sextoyse Hom...",
    "sub": "Marque · Cacuola",
    "price": "27,98 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0BRD4VZH5",
    "image": "https://m.media-amazon.com/images/I/31rDfpLF8fL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0BRD4VZH5?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 36,
    "cat": "sensualite",
    "name": "Sex Toys Anneau Penien - Anneau Homme Sextoyse Couple Pla...",
    "sub": "Marque · Glanvoo",
    "price": "25,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#1a1a1a",
    "asin": "B0BRN1QH85",
    "image": "https://m.media-amazon.com/images/I/41jcu05bt-L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0BRN1QH85?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 37,
    "cat": "erotisme",
    "name": "JUDUKU OSMOOZ Red - Jeu Couple - Jeux de société - Jeu de...",
    "sub": "Marque · ATM Gaming",
    "price": "15,99 €",
    "was": "19,99 €",
    "off": "-20%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0BF6192CK",
    "image": "https://m.media-amazon.com/images/I/31BlZNHDtFL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0BF6192CK?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 38,
    "cat": "erotisme",
    "name": "JUDUKU Jeu Couple - OSMOOZ Couple - 180 Cartes fabriquées...",
    "sub": "Marque · ATM Gaming",
    "price": "15,18 €",
    "was": "20,00 €",
    "off": "-24%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0926YDQNS",
    "image": "https://m.media-amazon.com/images/I/31H2t4pp6GL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0926YDQNS?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 39,
    "cat": "erotisme",
    "name": "CARTA SUTRA - Jeu Couple - Jeux de société - Jeu de Carte...",
    "sub": "Marque · CARTA SUTRA",
    "price": "29,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B09CB784JD",
    "image": "https://m.media-amazon.com/images/I/41hfFcN33nL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09CB784JD?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 40,
    "cat": "erotisme",
    "name": "Dimoi Jeu de Couple 240 Cartes pour entamer des Conversat...",
    "sub": "Marque · Tailemi",
    "price": "19,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B08DG3539L",
    "image": "https://m.media-amazon.com/images/I/31E1g1BoyqL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B08DG3539L?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 41,
    "cat": "erotisme",
    "name": "Oh Happy Games - Orgazmo - Le Jeu de Couple Ultime pour E...",
    "sub": "Marque · Oh Happy Games",
    "price": "19,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0CHN9FRGB",
    "image": "https://m.media-amazon.com/images/I/41f72NjEuYL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CHN9FRGB?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 42,
    "cat": "erotisme",
    "name": "CARTA SUTRA Action ou Vérité – Jeu Couple - Jeux de socié...",
    "sub": "Marque · CARTA SUTRA",
    "price": "24,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0DC71LB5M",
    "image": "https://m.media-amazon.com/images/I/41HUEHRPN4L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DC71LB5M?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 43,
    "cat": "erotisme",
    "name": "The Sensual Lab 54 Blocs – Jeux Couple – Relation & Compl...",
    "sub": "Marque · The Sensual Lab",
    "price": "18,98 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0FBRQG945",
    "image": "https://m.media-amazon.com/images/I/516gsIYhhzL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FBRQG945?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 44,
    "cat": "erotisme",
    "name": "LovBirdz, Quiz pour Couples | Cadeau Saint Valentin | Jeu...",
    "sub": "Marque · LOVBIRDZ",
    "price": "17,90 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0FFPG8LL9",
    "image": "https://m.media-amazon.com/images/I/41vMo7uoLAL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FFPG8LL9?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 45,
    "cat": "erotisme",
    "name": "Festi'Couple - Cap ou pas cap: 80 cartes pour jouer à deux",
    "sub": "Marque · MERCILESLIVRES",
    "price": "5,95 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "2383559946",
    "image": "https://m.media-amazon.com/images/I/41bIGG5DG9L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/2383559946?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 46,
    "cat": "erotisme",
    "name": "yilemeiyile 50 défis pour Adultes, Jeu de Couple Coquin: ...",
    "sub": "Marque · yilemeiyile",
    "price": "12,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0FM88FVLG",
    "image": "https://m.media-amazon.com/images/I/517PxRppWXL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FM88FVLG?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 47,
    "cat": "erotisme",
    "name": "Découverte Intime-Jeu Couples sans Tabou/120 Cartes Quest...",
    "sub": "Marque · Découverte Intime",
    "price": "19,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#3a1a26",
    "asin": "B0DVC8BSY4",
    "image": "https://m.media-amazon.com/images/I/31k2j4OsqUL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DVC8BSY4?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 48,
    "cat": "soins",
    "name": "Natessance huile de massage ylang ylang éveil des sens 100ml",
    "sub": "Marque · Natessance",
    "price": "5,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B015V1UVNS",
    "image": "https://m.media-amazon.com/images/I/31V-Als3A5L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B015V1UVNS?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 49,
    "cat": "soins",
    "name": "Huile de Massage Monoï, Relaxante et Aphrodisiaque, Hydra...",
    "sub": "Marque · bleu & marine Bretania",
    "price": "11,92 €",
    "was": "14,90 €",
    "off": "-20%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B01LBK1VIW",
    "image": "https://m.media-amazon.com/images/I/41AfEk+-m3L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B01LBK1VIW?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 50,
    "cat": "soins",
    "name": "QKnatur - Huile de Massage Relaxante fleur de Monoï - BIO...",
    "sub": "Marque · QKnatur",
    "price": "16,10 €",
    "was": "16,95 €",
    "off": "-5%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B09M7J3CQW",
    "image": "https://m.media-amazon.com/images/I/311OEAzu2VL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09M7J3CQW?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 51,
    "cat": "soins",
    "name": "LOVEA Huile de Massage Nourrissante Corps Multi-Usages Mo...",
    "sub": "Marque · Lovea",
    "price": "4,99 €",
    "was": "5,49 €",
    "off": "-9%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B0BYF9L893",
    "image": "https://m.media-amazon.com/images/I/31B+UKdusgL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0BYF9L893?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 52,
    "cat": "soins",
    "name": "WELEDA - Huile de Massage à l'Arnica - 200 ml",
    "sub": "Marque · Weleda",
    "price": "14,80 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B00D3HXGIA",
    "image": "https://m.media-amazon.com/images/I/31u7KEFKWZL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B00D3HXGIA?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 53,
    "cat": "soins",
    "name": "Yum'Lube - Huile de Massage Comestible Érotique Vanille -...",
    "sub": "Marque · Yum'Lube",
    "price": "16,90 €",
    "was": "19,90 €",
    "off": "-15%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B0CNZDGLH4",
    "image": "https://m.media-amazon.com/images/I/31-yipbCXTL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CNZDGLH4?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 54,
    "cat": "soins",
    "name": "Huile de massage à l'arnica Majestic Pure, 237 ml",
    "sub": "Marque · Majestic Pure",
    "price": "14,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B0F8V9GC1V",
    "image": "https://m.media-amazon.com/images/I/41agWKWYh5L._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0F8V9GC1V?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 55,
    "cat": "soins",
    "name": "Vibratissimo Hot Moments huile de massage chauffante et a...",
    "sub": "Marque · Vibratissimo",
    "price": "11,95 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B0BRT2T99X",
    "image": "https://m.media-amazon.com/images/I/41TWYH2QwYL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0BRT2T99X?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 56,
    "cat": "soins",
    "name": "Bougie de Massage Couple - Bougie Massage Sensuel Erotiqu...",
    "sub": "Marque · Sinful",
    "price": "14,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B0DDT6XH5N",
    "image": "https://m.media-amazon.com/images/I/41jepD8jmrL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0DDT6XH5N?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 57,
    "cat": "soins",
    "name": "Plaisirs Secrets Bougie de Massage Gourmande Parfum Ylang...",
    "sub": "Marque · Plaisirs Secrets",
    "price": "15,90 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B00SHHDB8G",
    "image": "https://m.media-amazon.com/images/I/41lrW-JhWML._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B00SHHDB8G?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 58,
    "cat": "soins",
    "name": "Plaisirs Secrets Bougie de Massage Gourmande Parfum Noix ...",
    "sub": "Marque · Plaisirs Secrets",
    "price": "17,44 €",
    "was": "17,95 €",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#c9a961",
    "asin": "B017797U5E",
    "image": "https://m.media-amazon.com/images/I/31gvGFuH+bL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B017797U5E?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 59,
    "cat": "cadeaux",
    "name": "YINUO LIGHT coffret cadeau de bougies parfumées pour femm...",
    "sub": "Marque · YINUO LIGHT",
    "price": "24,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0D4YVYXJZ",
    "image": "https://m.media-amazon.com/images/I/51yagU2JYmL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0D4YVYXJZ?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 60,
    "cat": "cadeaux",
    "name": "RSLOVE Ensemble de Lingerie Féminine avec Porte-Jarretell...",
    "sub": "Marque · RSLOVE",
    "price": "19,99 €",
    "was": "24,99 €",
    "off": "-20%",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0C6X52MRN",
    "image": "https://m.media-amazon.com/images/I/41Er0ZmpidL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0C6X52MRN?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 61,
    "cat": "cadeaux",
    "name": "Obsessive ensemble de lingerie guêpière avec string dans ...",
    "sub": "Marque · Obsessive",
    "price": "46,95 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B09RZTR4QN",
    "image": "https://m.media-amazon.com/images/I/413AJIkQnPL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09RZTR4QN?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 62,
    "cat": "cadeaux",
    "name": "TAHJOS Ensemble Lingerie Taille XXL pour Femmes Curvy – B...",
    "sub": "Marque · TAHJOS",
    "price": "9,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0H53945FQ",
    "image": "https://m.media-amazon.com/images/I/414297wlfoL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0H53945FQ?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 63,
    "cat": "cadeaux",
    "name": "Jarretière Dentelle Blanche Mariage - 1 Pièce avec Coffre...",
    "sub": "Marque · YongChiMaoYi",
    "price": "6,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0H95BHDLG",
    "image": "https://m.media-amazon.com/images/I/31-yjmL8KbL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0H95BHDLG?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 64,
    "cat": "cadeaux",
    "name": "Dstymkler Femmes sexy sangle arrière halter lingerie cost...",
    "sub": "Marque · Dstymkler",
    "price": "26,88 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0CN745J8Z",
    "image": "https://m.media-amazon.com/images/I/41HqWM5lJpL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CN745J8Z?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 65,
    "cat": "cadeaux",
    "name": "Obsessive ensemble de lingerie guêpière avec string dans ...",
    "sub": "Marque · Obsessive",
    "price": "46,95 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B09RZXHFMY",
    "image": "https://m.media-amazon.com/images/I/413AJIkQnPL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09RZXHFMY?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 66,
    "cat": "cadeaux",
    "name": "Obsessive Sensuel déshabillé ou Nuisette dans Un Magnifiq...",
    "sub": "Marque · Obsessive",
    "price": "34,95 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B09RZTQ6KQ",
    "image": "https://m.media-amazon.com/images/I/41CC1DCC6VL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B09RZTQ6KQ?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 67,
    "cat": "cadeaux",
    "name": "Blancrème Coffret Jeux de Massages Saveurs Gourmandes pou...",
    "sub": "Marque · Blancreme",
    "price": "24,90 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0CQKJLM7Y",
    "image": "https://m.media-amazon.com/images/I/51C1asyN4SL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0CQKJLM7Y?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  },
  {
    "id": 68,
    "cat": "cadeaux",
    "name": "Coffret Massages Amoureux - nouvelle édition",
    "sub": "Marque · Hugo Image",
    "price": "19,99 €",
    "was": "",
    "off": "",
    "rating": 0,
    "reviews": 0,
    "prime": false,
    "tag": "",
    "color": "#5b1a26",
    "asin": "B0FF44K9GF",
    "image": "https://m.media-amazon.com/images/I/310GNYnYOmL._SL500_.jpg",
    "url": "https://www.amazon.fr/dp/B0FF44K9GF?tag=lebrunnathali-21&linkCode=osi&th=1&psc=1"
  }
];

const PROMISES = [
  { kicker:'01', title:'Sélection éditoriale', body:'Maison Léa compare et organise des produits disponibles sur Amazon selon des critères utiles.' },
  { kicker:'02', title:'Prix vérifiés automatiquement', body:'Les prix sont affichés uniquement lorsqu\u2019ils ont été actualisés récemment via l\u2019API Amazon.' },
  { kicker:'03', title:'Transparence totale',          body:'Liens affiliés signalés clairement. Une commission Amazon nous rémunère, jamais vous.' },
  { kicker:'04', title:'Achat chez le vendeur',         body:'Vérifiez le vendeur, la livraison, les retours et la disponibilité directement sur Amazon.' },
];

const EDITORIAL = {
  kicker:'LE GUIDE · ÉDITION N°1',
  title:'Mes indispensables intimes.',
  excerpt:'Maison Léa partage une sélection éditoriale du moment, du soutien-gorge sans armatures au massage sensoriel. Prix et disponibilité sont confirmés sur Amazon.',
  read:'8 min'
};

const STATS = [
  { num:'68', label:'produits sélectionnés' },
  { num:'6', label:'territoires' },
  { num:'24h', label:'fraîcheur maximale des prix' },
  { num:'100%', label:'liens affiliés signalés' },
];

Object.assign(window, { AMAZON_DATA_UPDATED_AT, COLLECTIONS, PRODUCTS, PROMISES, EDITORIAL, STATS });
